from django import forms
from .models import Place

# any autogenerated/Model bound forms need to be made here
class NewPlaceForm(forms.ModelForm): 
    class Meta: # special class name... be sure to use this!
        model = Place
        fields= ('name','visited')